// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udgqabvondahhzqphyzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZ3FhYnZvbmRhaGh6cXBoeXpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTcyMDksImV4cCI6MjA3MTkzMzIwOX0.LYYrt4CpHqyo7AyTeynCIPbPbPQPTjCQuEpedZlrIdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});